In [1]:
import pandas as pd

In [9]:
df = pd.read_csv('movie_processed_data.csv')

In [10]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19925 entries, 0 to 19924
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       19925 non-null  object
 1   type          19925 non-null  object
 2   title         19925 non-null  object
 3   director      15712 non-null  object
 4   cast          19290 non-null  object
 5   country       10569 non-null  object
 6   date_added    10399 non-null  object
 7   release_year  19925 non-null  int64
 8   rating        19581 non-null  object
 9   duration      19922 non-null  object
 10  listed_in     19925 non-null  object
 11  description   19925 non-null  object
dtypes: int64(1), object(11)
memory usage: 1.8+ MB

In [16]:
df1 = pd.read_csv('movie_proccessed_data2.csv')

In [17]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19925 entries, 0 to 19924
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       19925 non-null  object
 1   type          19925 non-null  object
 2   title         19925 non-null  object
 3   director      14736 non-null  object
 4   cast          17677 non-null  object
 5   country       18688 non-null  object
 6   date_added    10399 non-null  object
 7   release_year  19925 non-null  int64
 8   rating        19581 non-null  object
 9   duration      19922 non-null  object
 10  listed_in     19925 non-null  object
 11  description   19925 non-null  object
dtypes: int64(1), object(11)
memory usage: 1.8+ MB

In [18]:
df1

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,113 min,"Comedy, Drama",A small fishing village must procure a local d...
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyonc√©, Britney...",United States,"March 30, 2021",2014,NaN,69 min,Documentary,"Pink breaks the mold once again, bringing her ..."
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,"March 30, 2021",1989,NaN,45 min,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...
...,...,...,...,...,...,...,...,...,...,...,...,...
19920,s1137,Movie,Planet of the Birds,NaN,Rodd Houston,United States,"November 12, 2019",2018,TV-PG,45 min,"Animals & Nature, Documentary, Family","Tough and versatile, birds live in almost ever..."
19921,s1205,TV Show,Spider-Man (Shorts),NaN,NaN,NaN,"November 12, 2019",2016,TV-Y7,1 Season,"Action-Adventure, Animation, Kids",Peter uses science to investigate his spider b...
19922,s1211,TV Show,Star Wars Rebels (Shorts),NaN,NaN,United States,"November 12, 2019",2014,TV-Y7,1 Season,"Action-Adventure, Animation, Kids",It is a dark time in the galaxy as the Empire ...
19923,s1260,TV Show,The Book of Once Upon a Time,NaN,Kate Mulvany,Australia,"November 12, 2019",2014,TV-Y,4 Seasons,"Animation, Anthology, Kids",Classic Disney tales are brought to life in a ...
19924,s1389,Movie,Tree Climbing Lions,NaN,Alexander Braczkowski,United States,"November 12, 2019",2018,TV-PG,45 min,"Animals & Nature, Documentary, Family","Lions in Uganda exhibit a rare, mysterious beh..."

In [19]:
df3 = df.merge(df1[['title', 'country']], on='title', how='left')

In [22]:
df3.drop('country_x',axis=1,inplace=True)

In [25]:
df3.to_csv('final_movie_shows.csv',index=False)